[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "target-feature=-mmx,-sse,+soft-float",
    "-C", "link-arg=-Tlinker.ld",
    "-C", "relocation-model=static",
]

[target.aarch64-unknown-none]
rustflags = [
    "-C", "target-feature=+soft-float,+strict-align",
    "-C", "link-arg=-Taarch64-linker.ld",
    "-C", "relocation-model=static",
]

# [target.'cfg(target_os = "none")']
# runner = "bootimage run"     # unused since bootloader crate v0.11 migration

[env]
SMOLTCP_IFACE_MAX_ADDR_COUNT = "4"
SMOLTCP_IFACE_MAX_ROUTE_COUNT = "4"
