[package]
name = "vahi-pci"
version = "0.3.0"
edition = "2021"
description = "PCI bus enumeration and configuration space access"

[dependencies]
spin = "0.9"
vahi-apic = { path = "../apic" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = { version = "0.14.2", default-features = false, features = ["instructions", "abi_x86_interrupt"] }
